### PR TITLE
Update Firmware Files to Marlin 2.0.5

### PR DESCRIPTION
**Pull request by MohanMaker**
I noticed that the uncompiled and precompiled Marlin firmware files in BIGTREETECH-SKR-E3-DIP-V1.0/Firmware are still Marlin version 2.0.0. The latest version of Marlin is 2.0.5 (released 3/14/20), so I went through and created updated uncompiled and precompiled files (using the source code from the official Marlin repository). All of the settings and configurations in the configuration.h, configuration_adv.h, and platformio.ini files are the same as they were originally. I've also tested the new firmware files on my own SKR E3 DIP (using TMC2209 drivers) and they work perfectly. Thanks, @bigtreetech!

### CODE REVIEW

**Comment by stockHuman** [comment]
Thanks a lot, @MohanMaker! Can confirm it works wonderfully on my E3Pro with TMC2208's.

**Comment by MohanMaker** [comment]
Glad that it works for you @stockHuman! @bigtreetech, could you take a moment to review this pull request and merge it into the repository? Thanks!

**Comment by DismissedGuy** [comment]
I just gave this a shot and it works great for me as well. It would be nice if this got merged.

**Comment by jgoldrich** [comment]
This file gives me TMC connection error. any ideas?

**Pull request merged**
