### PR TITLE
pull request from master

### PR DESCRIPTION
**Pull request by Ofloo**
master pull request

### CODE REVIEW

**Comment by MohanMaker** [comment]
Dear Ofloo, please explain the purpose of this pull request. It seems that many of the changes you are submitting are specific to your printer, so I am not quite sure why you are trying to merge this to this repository. Thanks!

**Comment by Ofloo** [comment]
I'm very sorry I didn't intend to pull from my repo to the bigtreerepo but visa versa.

**Comment by MohanMaker** [comment]
No problem, thanks for letting us know. In that case, would it be possible for you to close this Pull Request?

**Comment by Ofloo** [comment]
Sorry wasn't even aware it was there. Not sure if this is how i close it but i'll close and comment below and hope it's closed then.

**Pull request closed without merging**
